name: "My First GitHub Action"

on: [push]

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "Print Hello World"
        run: echo "Hello World!"

      - name: "Print some linux commands"
        run: |
          echo "Current Directory:"
          pwd
          echo "List of Files:"
          ls -la
        
      - name: "Print Readme File"
        run: cat README.md

      - name: "Generate ASCII Artwork"
        run: cowsay "GitHub Actions are awesome!" >> ascii_art.txt