name: "Generate ASCII Artwork"

on: [push]

jobs:
  ascii_art_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "List Repository Files"
        run: ls -latr
      
      - name: "Running ASCII Art Generator... script"
        run: sh ascii-script.sh

