name: "Generate ASCII Artwork"

on: [push]

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "List Repository Files"
        run: ls -latr
      
      - name: "Running ASCII Art Generator... script"
        run: sh ascii-script.sh

      - name: "Upload ASCII Art as artifact as a text file"
        uses: actions/upload-artifact@v6
        with:
          name: dragon-artifact
          path: dragon.txt

  test_job:
    runs-on: ubuntu-latest
    needs: build_job
    steps:
      - name: "Download ASCII Art artifact"
        uses: actions/download-artifact@v7
        with:
          name: dragon-artifact
      
      - name: "Artifact existence"
        run: |
          if [ -f "dragon.txt" ]; then
            echo "File exists."
          else
            echo "File does not exist."
            exit 1
          fi
  deploy_job:
    runs-on: ubuntu-latest
    needs: [test_job]
    steps:
      - name: "Download ASCII Art artifact for deployment"
        uses: actions/download-artifact@v7
        with:
          name: dragon-artifact

      - name: "Reading ASCII Art from dragon.txt"
        run: cat dragon.txt

      - name: "Deploying ASCII Art"
        run: echo "Deploying ASCII Art to production..."
